version: "3.9"

services:
  dev: &dev
    profiles:
      - dev
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    environment:
      DATABASE_URL: postgres://local-dev@db/api?sslmode=disable
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    links:
      - db
    command: go run cmd/cli/main.go bot run

  scheduler:
    <<: *dev
    profiles:
      - app
    command: app scheduler run

  bot:
    <<: *dev
    profiles:
      - app
    command: app bot run

  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: local-dev
      POSTGRES_HOST_AUTH_METHOD: trust

  migrate: &basemigrate
    profiles: [ "tools" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""

volumes:
  data:

