version: "3.9"

x-common-variables: &common-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}

services:
  dev: &dev
    profiles:
      - dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    environment:
      <<: *common-variables
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    links:
      - db
    command: go run cmd/cli/main.go bot run

  scheduler:
    <<: *dev
    build:
      dockerfile: Dockerfile
      context: .
      target: built
    profiles:
      - app
    command: app scheduler run

  bot:
    <<: *dev
    build:
      dockerfile: Dockerfile
      context: .
      target: built
    profiles:
      - app
    command: app bot run

  db:
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      <<: *common-variables
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  migrate: &basemigrate
    profiles: [ "tools" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://${POSTGRES_USER}@db/${POSTGRES_DB}?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./migrations:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""

volumes:
  data:

